# Generated by Django 4.2.3 on 2023-09-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_options_alter_topic_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='views_nums',
            field=models.ManyToManyField(to='blog.viewnumber'),
        ),
    ]
