# Generated by Django 4.2.3 on 2023-09-29 16:12

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_viewcount_remove_blog_views_nums_delete_viewnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='viewers',
            field=models.ManyToManyField(blank=True, to='blog.viewcount', verbose_name='Просмотры'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='blog_blog_search__af343e_gin'),
        ),
    ]
